db:
  environment:
    POSTGRES_DB: my_app
    POSTGRES_PASSWORD: changeme
    POSTGRES_USER: my_app
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: postgres:9.6
  stdin_open: true
redis:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: redis:3.0-alpine
  stdin_open: true
queue:
  environment:
    APP_ENV: staging
    APP_URL: http://www.mydomain.com
    CACHE_DRIVER: redis
    QUEUE_DRIVER: redis
    DB_DATABASE: my_app
    DB_USERNAME: my_app
    DB_PASSWORD: changeme
  labels:
    io.rancher.container.pull_image: always
  command:
  - php
  - /var/www/html/artisan
  - queue:listen
  - --sleep=3
  tty: true
  image: realpage/laravel-starter:cli.staging.[HASH]
  stdin_open: true
migrations:
  environment:
    APP_ENV: staging
    CACHE_DRIVER: redis
    DB_DATABASE: my_app
    DB_USERNAME: my_app
    DB_PASSWORD: changeme
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  command:
  - php
  - artisan
  - migrate
  - --force
  tty: true
  image: realpage/laravel-starter:cli.staging.[HASH]
  stdin_open: true
reset-database:
  environment:
    APP_ENV: staging
    CACHE_DRIVER: redis
    DB_DATABASE: my_app
    DB_USERNAME: my_app
    DB_PASSWORD: changeme
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  command:
  - php
  - infrastructure/reset_environment.php
  log_opt: {}
  image: realpage/laravel-starter:cli.staging.[HASH]
  stdin_open: true
web:
  ports:
  - 4443:2443/tcp
  - 4000:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: realpage/laravel-starter:nginx.staging.[HASH]
  links:
  - 'fpm:'
  stdin_open: true
fpm:
  environment:
    APP_ENV: staging
    APP_KEY: [APP_KEY]
    APP_URL: http://www.mydomain.com
    CACHE_DRIVER: redis
    QUEUE_DRIVER: redis
    DB_DATABASE: my_app
    DB_USERNAME: my_app
    DB_PASSWORD: changeme
    DB_PORT: '5432'
    HEALTHCHECK_TOKEN: [HEALTHCHECK_TOKEN]
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: realpage/laravel-starter:fpm.staging.[HASH]
  links:
  - db:db
  stdin_open: true
